#!/bin/bash

# Change to be whatever
FQDN="$1"
EMAIL="$2"
ADMIN="$3"
HOMEDIR="/home/imovies/appliedseclab/bash/"
SERIAL=$(cat ${HOMEDIR}demoCA/serial)
# make directories to work from
mkdir -p ${HOMEDIR}certs/{users,tmp}

# Create Certificate for this domain,
mkdir -p "${HOMEDIR}certs/users/${FQDN}"
openssl genrsa \
  -out "${HOMEDIR}certs/users/${FQDN}/${SERIAL}.key.pem" \
  2048

# Create the CSR
openssl req -new \
  -key "${HOMEDIR}certs/users/${FQDN}/${SERIAL}.key.pem" \
  -out "${HOMEDIR}certs/tmp/${FQDN}.csr.pem" \
  -subj "/C=CH/ST=Zurich/L=Zurich/O=iMovies/OU=${ADMIN}/CN=${FQDN}/emailAddress=${EMAIL}"

#Sign the request from with your root CA
openssl x509\
  -req -in "${HOMEDIR}certs/tmp/${FQDN}.csr.pem" \
  -CA "${HOMEDIR}certs/ca/my-root-ca.crt.pem"\
  -CAkey "${HOMEDIR}certs/ca/my-root-ca.key.pem" \
  -CAserial "${HOMEDIR}demoCA/serial"\
  -out "${HOMEDIR}certs/users/${FQDN}/${SERIAL}.crt.pem" \
  -days 9131

#remove csr file
rm "${HOMEMDIR}certs/tmp/${FQDN}.csr.pem"


#exports to pkcs12 file uname.p12
openssl pkcs12 \
  -export \
  -inkey "${HOMEDIR}certs/users/${FQDN}/${SERIAL}.key.pem"\
  -in "${HOMEDIR}certs/users/${FQDN}/${SERIAL}.crt.pem"\
  -out "${HOMEDIR}certs/users/${FQDN}/${FQDN}.p12" \
  -passout pass: 


#file has been generated, increment generated by one
gawk -i inplace '{$1=$1+1}1' ${HOMEDIR}demoCA/generated

#rename files
#NEWSERIAL=$(cat demoCA/serial)
#mv certs/users/${FQDN}/${SERIAL}.key.pem certs/users/${FQDN}/${NEWSERIAL}.key.pem
#mv certs/users/${FQDN}/${SERIAL}.crt.pem certs/users/${FQDN}/${NEWSERIAL}.crt.pem

#writes corresponding serial number to stdout
echo ${NEWSERIAL}
