#!/bin/bash

# Change to be whatever
FQDN="$1"
EMAIL="$2"
ADMIN="$3"
SERIAL=$(cat demoCA/serial)

# make directories to work from
mkdir -p certs/{users,tmp}

# Create Certificate for this domain,
mkdir -p "certs/users/${FQDN}"
openssl genrsa \
  -out "certs/users/${FQDN}/${SERIAL}.key.pem" \
  2048

# Create the CSR
openssl req -new \
  -key "certs/users/${FQDN}/${SERIAL}.key.pem" \
  -out "certs/tmp/${FQDN}.csr.pem" \
  -subj "/C=CH/ST=Zurich/L=Zurich/O=iMovies/OU=${ADMIN}/CN=${FQDN}/emailAddress=${EMAIL}"

#Sign the request from with your root CA
openssl x509\
  -req -in "certs/tmp/${FQDN}.csr.pem" \
  -CA "certs/ca/my-root-ca.crt.pem"\
  -CAkey "certs/ca/my-root-ca.key.pem" \
  -CAserial "demoCA/serial"\
  -out "certs/users/${FQDN}/${SERIAL}.crt.pem" \
  -days 9131

#remove csr file
rm "certs/tmp/${FQDN}.csr.pem"

#sleep 0.1

#exports to pkcs12 file uname.p12
openssl pkcs12 \
  -export \
  -inkey "certs/users/${FQDN}/${SERIAL}.key.pem"\
  -in "certs/users/${FQDN}/${SERIAL}.crt.pem"\
  -out "certs/users/${FQDN}/${FQDN}.p12" \
  -passout pass: 

#TODO make the key and certificate files mode 600

#file has been generated, increment generated by one
gawk -i inplace '{$1=$1+1}1' demoCA/generated

#writes corresponding serial number to stdout
echo ${SERIAL}
